name: Update File Metadata

on:
  push:
  workflow_dispatch:

  

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v4  # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13 # Install the python version needed

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip requests

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com" 
          
      - name: Get Updated Files
        env:  
            GIT_SHA: ${{ github.sha }}
        run: |
         echo "FILES={git diff-tree --no-commit-id --name-only -r ${{ github.sha }}}" 
         echo "Changed files: $FILES"
         echo "::set-output name=files::$FILES"

      - name: Execute Auto-Update Python Script
        run: python .github/workflows/scripts/updatefileinfo.py $FILES

      - name: Stage, Commit and Push 
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add $FILES
          git commit -m "[Automation] Updated Simulation File."
          git push origin main
