name: Build VGA Playground Simulation File

on:
  workflow_dispatch:

permissions:
    contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python .github/workflows/scripts/buildsim.py src/tt_um_Enjimneering_full_adder.v -t tt_um_Enjimneering_full_adder  -o simulation/vga_playground.v
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"    
          
      - name: Stage Commit and Push 
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add simulation/vga_playground.v
          git commit -m "AUTOMATION: Built Simulation File."
          git push origin main
