name: Build VGA Playground Simulation File

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python .github/workflows/scripts/buildsim.py src/tt_um_Enjimneering_full_adder.v -t tt_um_Enjimneering_full_adder  -o simulation/vga_playground.v
            
      - name: stage changed files
        run: git add simulation/vga_playground.v
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: commit changed files
        run: git commit -m "Built VGA Simulation File."
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: fetch from main
        run: git fetch origin main
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: push code to master
        run: git push origin HEAD:main
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
